// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_middleware from "./routes/account/_middleware.ts";
import * as $account_index from "./routes/account/index.tsx";
import * as $api_email_availability_middleware from "./routes/api/email-availability/_middleware.ts";
import * as $api_email_availability_index from "./routes/api/email-availability/index.ts";
import * as $api_generate_authentication_options from "./routes/api/generate-authentication-options.ts";
import * as $api_handle_availability from "./routes/api/handle-availability.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_password_strength from "./routes/api/password-strength.ts";
import * as $api_user_middleware from "./routes/api/user/_middleware.ts";
import * as $api_user_index from "./routes/api/user/index.ts";
import * as $api_user_passkey_delete from "./routes/api/user/passkey/delete.ts";
import * as $api_user_passkey_edit from "./routes/api/user/passkey/edit.ts";
import * as $api_user_passkey_register_request from "./routes/api/user/passkey/register-request.ts";
import * as $api_user_passkey_verify_registration from "./routes/api/user/passkey/verify-registration.ts";
import * as $api_verify_authentication from "./routes/api/verify-authentication.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $signup_index from "./routes/signup/index.tsx";
import * as $EmailInput from "./islands/EmailInput.tsx";
import * as $HandleInput from "./islands/HandleInput.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $PasskeyEditDelete from "./islands/PasskeyEditDelete.tsx";
import * as $PasswordInput from "./islands/PasswordInput.tsx";
import * as $PasswordPairInputs from "./islands/PasswordPairInputs.tsx";
import * as $PasswordStrengthIndicator from "./islands/PasswordStrengthIndicator.tsx";
import * as $RegisterPasskey from "./islands/RegisterPasskey.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/_middleware.ts": $account_middleware,
    "./routes/account/index.tsx": $account_index,
    "./routes/api/email-availability/_middleware.ts":
      $api_email_availability_middleware,
    "./routes/api/email-availability/index.ts": $api_email_availability_index,
    "./routes/api/generate-authentication-options.ts":
      $api_generate_authentication_options,
    "./routes/api/handle-availability.ts": $api_handle_availability,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/password-strength.ts": $api_password_strength,
    "./routes/api/user/_middleware.ts": $api_user_middleware,
    "./routes/api/user/index.ts": $api_user_index,
    "./routes/api/user/passkey/delete.ts": $api_user_passkey_delete,
    "./routes/api/user/passkey/edit.ts": $api_user_passkey_edit,
    "./routes/api/user/passkey/register-request.ts":
      $api_user_passkey_register_request,
    "./routes/api/user/passkey/verify-registration.ts":
      $api_user_passkey_verify_registration,
    "./routes/api/verify-authentication.ts": $api_verify_authentication,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login/index.tsx": $login_index,
    "./routes/signup/index.tsx": $signup_index,
  },
  islands: {
    "./islands/EmailInput.tsx": $EmailInput,
    "./islands/HandleInput.tsx": $HandleInput,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/PasskeyEditDelete.tsx": $PasskeyEditDelete,
    "./islands/PasswordInput.tsx": $PasswordInput,
    "./islands/PasswordPairInputs.tsx": $PasswordPairInputs,
    "./islands/PasswordStrengthIndicator.tsx": $PasswordStrengthIndicator,
    "./islands/RegisterPasskey.tsx": $RegisterPasskey,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
